#!/usr/bin/env bash

PRJ=nullpointer
HOST_PORT=80
CONTAINER_PORT=80

docker build -t $PRJ .
docker rename "$PRJ" "$PRJ-1"
docker stop "$PRJ-1"
docker run -d -p $HOST_PORT:$CONTAINER_PORT --name="$PRJ" $PRJ
docker rm "$PRJ-1"
